# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_RXSwift_Cars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_RXSwift_Cars
  pod 'RxSwift', '4.5'
  pod 'RxCocoa', '4.5'

  target 'MVVM_RXSwift_CarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM_RXSwift_CarsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
